Repository IrynaZakharchenko/LibraryManagementSystem, pull requests merged in 2018-12, with the labels that each got.

#27 Changed view book information
  src/LMSController/BookFinding.cs
  src/LMSController/BookInformation.cs
  src/LMSController/StockmanWorkspace.cs
  src/LMSView/BookInfoControlForm.Designer.cs
  src/LMSView/BookInfoControlForm.cs
  src/LMSView/BookInfoControlForm.resx
  src/LMSView/BookLibraryInfoControlForm.Designer.cs
  src/LMSView/BookLibraryInfoControlForm.cs
  src/LMSView/ClientLibraryInfoControlForm.Designer.cs
  src/LMSView/InventoryCodeControlForm.Designer.cs
  src/LMSView/InventoryCodeControlForm.cs
  src/LMSView/InventoryCodeControlForm.resx
  src/LMSView/LMSView.csproj
  src/LMSView/Properties/Resources.Designer.cs
  src/LMSView/Properties/Resources.resx
Labels: UI, bug

#33 Small fixes
  src/LMSController/AuthorInformation.cs
  src/LMSController/BookFinding.cs
  src/LMSController/IBookFinding.cs
  src/LMSController/ILibrararyOperations.cs
  src/LMSController/IPublishHouseInformationRegister.cs
  src/LMSController/LibraryOperations.cs
  src/LMSController/PublishHouseInformationRegister.cs
  src/LMSController/StockmanWorkspace.cs
  src/LMSModel/Accounts.cs
  src/LMSModel/Books.cs
  src/LMSModel/LMSModel.csproj
  src/LMSModel/Library.cs
  src/LMSModel/PublishingHouses.cs
  src/LMSView/BookInfoControlForm.cs
  src/LMSView/PublishHouseControlForm.cs
  src/LMSView/UserInformationControlForm.cs
Labels: bug

#34 Implementation and documentation
  src/LMSController/BookFinding.cs
  src/LMSController/ILibrararyOperations.cs
  src/LMSController/LMSController.csproj
  src/LMSController/LibraryOperations.cs
  src/LMSController/doc/LMSControllerAdministrator.cd
  src/LMSController/doc/LMSControllerInterfaces.cd
  src/LMSController/doc/LMSControllerLibrarian.cd
  src/LMSController/doc/LMSControllerStockman.cd
  src/LMSModel/Library.cs
  src/LMSView/BookInfoControlForm.cs
  src/LMSView/LMSView.csproj
  src/LMSView/doc/LMSView.cd
  src/LMSView/doc/LMSViewAdministrator.cd
  src/LMSView/doc/LMSViewLibrarian.cd
  src/LMSView/doc/LMSViewStockman.cd
Labels: diploma, doc, enhancement

#35 Diploma improve
  diploma_notes/MyDiploma.docx
Labels: diploma

#39 Raw implementation of Librarian use cases
  src/LMSController/administrator/UserInformationRegister.cs
  src/LMSController/librarian/ClientInformationRegister.cs
  src/LMSController/librarian/ILibraryCardRegister.cs
  src/LMSController/librarian/LibraryCardRegister.cs
  src/LMSController/types/ClientInformation.cs
  src/LMSController/types/PersonalInformation.cs
  src/LMSModel/Bibliographies.cs
  src/LMSModel/LMSModel.csproj
  src/LMSModel/Readers.cs
  src/LMSView/ClientLibraryInfoControlForm.cs
Labels: enhancement
